#ifndef JSON_CONFIG_H
#define JSON_CONFIG_H

#define MAX_KEY_LENGTH 256
#define MAX_KEYS_IN_OBJECT 256
#define MAX_ARRAY_LENGTH 800
#define MAX_STRING_LENGTH 5000
#define MAX_JSON_LENGTH 50000
#define MAX_LINE_LENGTH 6000
#define MAX_KEYS_IN_INPUT 35
#define VALUE_DELIMITER ','

enum JSON_DATA_TYPES {
    JSON_INTEGER,
    JSON_REAL,
    JSON_STRING,
    JSON_TRUE,
    JSON_FALSE,
    JSON_ARRAY,
    JSON_OBJECT,
    JSON_NULL
};


#endif //JSON_CONFIG_H